---
title: "New York Times Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{new-york-times}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(covdata)
library(tidyverse)
```

## National, State- and County-Level (Cumulative) Data from the _New York Times_

```{r nyt-us}
nytcovus
```


```{r nyt-state}
nytcovstate
```

```{r nyt-county}
nytcovcounty
```


Draw a log-linear graph of cumulative US cases by county.

```{r nytplot,  fig.height=15, fig.width=8, dpi=150}
nytcovcounty %>%
  mutate(uniq_name = paste(county, state)) %>% # Can't use FIPS because of how the NYT bundled cities
  group_by(uniq_name) %>%
  mutate(days_elapsed = date - min(date)) %>%
  ggplot(aes(x = days_elapsed, y = cases, group = uniq_name)) + 
  geom_line(size = 0.25, color = "gray20") + 
  scale_y_log10(labels = scales::label_number_si()) + 
  guides(color = FALSE) + 
  facet_wrap(~ state, ncol = 5) + 
  labs(title = "COVID-19 Cumulative Recorded Cases by US County",
       subtitle = paste("New York is bundled into a single area in this data.\nData as of", format(max(nytcovcounty$date), "%A, %B %e, %Y")),
       x = "Days since first case", y = "Count of Cases (log 10 scale)", 
       caption = "Data: The New York Times | Graph: @kjhealy") + 
  theme_minimal()

```
